### ISSUE TITLE
Data Overflow

### ISSUE THREAD

**Issue by vext01** [jcharra/meowbg#1]
Hi,

I was looking for an open source FIBS client and well, I found one. Looks like a solid start.

I managed to play against a bot for a few turns before seeing:

```
 I just received an event <meowbg.core.events.RollRequest object at 0x175afc03dfd0>
 I just received an event <meowbg.core.events.RollRequest object at 0x175afc03dfd0>
 I just received an event <meowbg.core.events.RollRequest object at 0x175afc03dfd0>
 I just received an event <meowbg.core.events.RollRequest object at 0x175afc03dfd0>
 I just received an event <meowbg.core.events.RollRequest object at 0x175afc03dfd0>
[WARNING] ** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow

** Data overflow


 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
 Not parseable: '** Data overflow'
```

Cheers

**Comment by jcharra** [comment]
Hi, thanks for the report. 

I haven't been working on this project for some time, I'll look into this problem as soon as I find the time to do so. Currently you always log on to the Tigergammon server with a fixed username/pw combination ... server selection and credentials input fields are two of the next things to build, definitely. ;)

Best regards,
Johannes

**Comment by Watzmann** [comment]
'** Data overflow' is a message issued by the server when it detects a (supposed) bot attack. This behaviour was introduced about in April 2014. It then ignores consequent input until the spam detection module has cooled down again.

Andreas

**Comment by jcharra** [comment]
There was indeed a major bug, causing instances of a class to pile up with every match status coming from the server ... this has been fixed by https://github.com/jcharra/meowbg/commit/07a2bb9251bd35740560fb497353570d04ae7872

**Comment by vext01** [comment]
On Tue, Mar 17, 2015 at 02:39:28PM -0700, Johannes Charra wrote:
> There was indeed a major bug, causing instances of a class to pile up with every match status coming from the server ... this has been fixed by https://github.com/jcharra/meowbg/commit/07a2bb9251bd35740560fb497353570d04ae7872
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jcharra/meowbg/issues/1#issuecomment-82609805

Thanks!

-- 
Best Regards
Edd Barrett

http://www.theunixzoo.co.uk
